### ISSUE TITLE
lowercase for linux compatibility

### ISSUE THREAD

**Issue by boLekc** [Rod-Serling/AVS#1]
can you please use lowercase for linux compatibility :)

**Comment by Rod-Serling** [comment]
Lowercase where? in all the file names? Please be specific, as I don't have much experience with linux.

**Comment by boLekc** [comment]
only the main folder ^^

has just not worked because i forgot to add a line

**Comment by Rod-Serling** [comment]
Why exactly does that need to be lower case? That's only used to create a PBO out of, you can make the PBO lowercase.

**Comment by Gr8z** [comment]
You can use uppercase in linux as long as its called correctly, in this case, it is. 
Therefore this is not a real problem.
