### ISSUE TITLE
Battleye Remotexec log

### ISSUE THREAD

**Issue by Spackler** [Rod-Serling/AVS#4]
I am getting the following in my remote exex log. Any ideas?
# 0 "avs_fnc_refuelpayment ["DwbiNoYk",R :1 (Spackler) REMOTE,-250,false]"

**Comment by Vandest1** [comment]
Have you merge your "description.ext" with that of mod, like explain in "Installation.txt" ?

**Comment by Vandest1** [comment]
If yes, add this line in your remoteexec.txt (Line 2):
!="avs_fnc_refuelpayment \[.*,.*\]"
